# Use custom format
# format = """
# [┌───────────────────>](bold green)
# [│](bold green)$directory$rust$package
# [└─>](bold green) """

# Don't print a new line at the start of the prompt
add_newline = false

# Make prompt a single line instead of two lines
[line_break]
disabled = false


# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

# Replace the "❯" symbol in the prompt with "➟"
[character]      # The name of the module we are configuring is "character"
use_symbol_for_status = true
symbol = "➟ "     # The "symbol" segment is being set to "➜"
error_symbol = "✗ "
style_success = "bold #00A652"
style_failure = "bold #df382c"

# configure directory
[directory]
truncation_length = 10
truncate_to_repo = true # truncates directory to root folder if in github repo

[username]
disabled = true
